### ISSUE TITLE
improvement suggestion about some -er

### ISSUE THREAD

**Issue by kayhantolga** [mertnesvat/Habit-Stack#2]
- Work it harder
- Make it better
- Do it faster
- Makes us stronger

**Comment by mertnesvat** [comment]
@kayhantolga right away sir!

**Comment by kayhantolga** [comment]
Sorry, My wifi is not working! Can you reopen the issue?

- Work it harder
- Make it better
- Do it faster
- Makes us stronger

**Comment by mertnesvat** [comment]
@kayhantolga #1 I'll give you the meaning of life now > close it open it again! 🥇

**Comment by kayhantolga** [comment]
I saw a light on my wifi wires.
